### ISSUE TITLE
Default Valign & HAlign are not the game defaults

### ISSUE THREAD

**Issue by oliverde8** [steeffeen-zz/FancyManiaLinks#40]
Hi, by default you set

```
$horizontalAlign = self::CENTER;
// And
$verticalAlign = self::CENTER2;
```

But this doesn't correspond to the game defaults when the values are left empty. 

This is very annoying when you build you ML using the ingame MLBuilder & then try and reproduce it with FML. You need everytime to set the alignements manually. 

Thanks

**Comment by steeffeen-zz** [comment]
Hi @oliverde8,
I used these default values since the beginning because I built my ManiaLinks with centered position all the time.
I totally agree that coming from the interface builder makes it quite painful.
Considering that existing ManiaLinks would be broken if the default values were to be changed, I think there needs to be a way to set these defaults. For now you could do that locally in the FML source files until there is a programmatic way of achieving this.
Cheers,
Steffen

**Comment by oliverde8** [comment]
Hi, 

I use composer to install FML so changing the source code isn't an option for me, 😄 

I do a setAlign(null, null) foreach element I create but it make it quite a pain. but I will continue this way until you make a fix that won't break other ML

**Comment by steeffeen-zz** [comment]
Alright. :)
Anyways, thanks for the request. I will try to solve it shortly!

**Comment by oliverde8** [comment]
Take your time, and I veeeery far from having something to show so I don't mind leaving it like this for a while.

**Comment by steeffeen-zz** [comment]
Btw. there is also a convenience method for ->setAlign(null, null): That is ->clearAlign(). :)
In return ->centerAlign() resets it to the default centered position.

**Comment by steeffeen-zz** [comment]
With the latest commit there are new methods to change the default alignment statically (once for all controls):
Control::clearDefaultAlign();
Control::centerDefaultAlign();
Control::setDefaultHorizontalAlign("halign");
Control::setDefaultVerticalAlign("valign");
